/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness: the process is running
         * @description Touches no dependency, so it stays 200 while the database is down.
         */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness: the process can serve traffic
         * @description Runs `SELECT 1` against MySQL, bounded by HEALTH_TIMEOUT_MS.
         */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller’s own account
         * @description The first call after a login creates the account from the access token’s profile claims (name, email, picture); later calls return the same id. `verified` follows the token’s `email_verified`.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish (or skip) first-login onboarding
         * @description Sets `onboarded` on `GET /v1/me`. Idempotent: a repeat call keeps the first timestamp.
         */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller’s editable profile header */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change profile header fields
         * @description Any non-empty subset of the fields. `null` (or a blank string) clears a nullable field; `links` changes only the keys it names. Unknown keys are rejected, so `verified`, `email` and the like cannot be written. `isPublic: false` hides the profile from everyone but the owner immediately.
         */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A profile with its sections
         * @description Needs no token when the profile is public; a token, when sent, identifies the owner (`isOwner`). A private profile answers 404 to everyone but its owner, exactly as an unknown id does. A token that is sent but invalid is a 401, not an anonymous read. Never includes birthday, phone, the login email or any token.
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description Stable machine-readable code. Branch on this, never on `message`.
             * @example NOT_FOUND
             */
            code: string;
            /** @description Human-readable; not part of the contract. */
            message: string;
            /** @description Field-level detail, for VALIDATION_FAILED only. */
            details?: unknown;
        };
        Certification: {
            id: string;
            name: string;
            issuer: string;
            /**
             * @description YYYY-MM
             * @example 2025-01
             */
            date: string;
            credentialUrl: string | null;
        };
        Education: {
            id: string;
            institution: string;
            degree: string;
            field: string;
            startYear: number;
            /** @description null: still studying. */
            endYear: number | null;
            description: string | null;
            highlights: string[];
        };
        Experience: {
            id: string;
            title: string;
            organization: string;
            /**
             * @description YYYY-MM
             * @example 2024-06
             */
            start: string;
            /** @description YYYY-MM; null: present. */
            end: string | null;
            summary: string;
            achievements: string[];
            skills: string[];
        };
        Profile: {
            id: string;
            name: string;
            headline: string;
            bio: string | null;
            location: string | null;
            avatarUrl: string | null;
            verified: boolean;
            contactEmail: string | null;
            links: components["schemas"]["ProfileLinks"];
            /** @description The caller is the profile owner. */
            isOwner: boolean;
            isPublic: boolean;
            education: components["schemas"]["Education"][];
            experience: components["schemas"]["Experience"][];
            certifications: components["schemas"]["Certification"][];
            skills: string[];
            /** @description Own and accepted-team projects, newest first. Others see public, published ones only; the owner also sees their own private and draft ones. */
            projects: components["schemas"]["ProfileProject"][];
        };
        ProfileHeader: {
            id: string;
            name: string;
            headline: string;
            /** @description Plain text. Never HTML. */
            bio: string | null;
            location: string | null;
            /** @description An http(s) URL (URL-only until M4). */
            avatarUrl: string | null;
            /** @description Public contact address the user chose. Not the login email. */
            contactEmail: string | null;
            /** @description false: only the owner can read the profile. */
            isPublic: boolean;
            links: components["schemas"]["ProfileLinks"];
        };
        ProfileLinks: {
            github: string | null;
            linkedin: string | null;
            twitter: string | null;
            website: string | null;
        };
        ProfileProject: {
            id: string;
            title: string;
            summary: string | null;
            /** @enum {string} */
            category: "academic" | "personal" | "research" | "hackathon" | "course" | "other";
            /** @enum {string} */
            status: "ongoing" | "completed" | "archived";
            heroImageUrl: string | null;
            tags: string[];
            /**
             * @description owner: the profile owner created it; member: accepted team member.
             * @enum {string}
             */
            role: "owner" | "member";
            isPublic: boolean;
            isDraft: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** @enum {string} */
                        database: "ok";
                    };
                };
            };
            /** @description DATABASE_UNAVAILABLE: MySQL is unreachable or too slow */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller’s account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description The user id (UUID)
                         * @example 0b6f2c1e-…
                         */
                        id: string;
                        name: string;
                        email: string | null;
                        avatarUrl: string | null;
                        headline: string;
                        /** @description Email verified with Auth0 (GitHub from M7). */
                        verified: boolean;
                        isPublic: boolean;
                        /** @description false: the frontend should offer first-login onboarding. */
                        onboarded: boolean;
                        /** @description Login providers linked to the account, e.g. `google-oauth2`. */
                        identities: string[];
                    };
                };
            };
            /** @description UNAUTHENTICATED: no access token, or one that is invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: over budget; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AUTH_UNAVAILABLE: Auth0 signing keys unreachable, or DATABASE_UNAVAILABLE: MySQL unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Onboarding is complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        onboarded: true;
                    };
                };
            };
            /** @description UNAUTHENTICATED: no access token, or one that is invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: the account no longer exists */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: over budget; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AUTH_UNAVAILABLE: Auth0 signing keys unreachable, or DATABASE_UNAVAILABLE: MySQL unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The header */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileHeader"];
                };
            };
            /** @description UNAUTHENTICATED: no access token, or one that is invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: the account no longer exists */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: over budget; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AUTH_UNAVAILABLE: Auth0 signing keys unreachable, or DATABASE_UNAVAILABLE: MySQL unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    headline?: string;
                    bio?: (null) | string;
                    location?: (null) | string;
                    avatarUrl?: (null) | string;
                    contactEmail?: (null) | string;
                    isPublic?: boolean;
                    links?: {
                        github?: (null) | string;
                        linkedin?: (null) | string;
                        twitter?: (null) | string;
                        website?: (null) | string;
                    };
                };
            };
        };
        responses: {
            /** @description The header after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileHeader"];
                };
            };
            /** @description VALIDATION_FAILED: the body does not fit the schema (see `details`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED: no access token, or one that is invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: the account no longer exists */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: over budget; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AUTH_UNAVAILABLE: Auth0 signing keys unreachable, or DATABASE_UNAVAILABLE: MySQL unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description UNAUTHENTICATED: a token was sent and is invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: no such profile, or it is private and the caller is not its owner */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: over budget; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AUTH_UNAVAILABLE or DATABASE_UNAVAILABLE */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
