import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SideBarWrapper } from "@/components/sidebar/SideBarWrapper";
import { SidebarVisibilityProvider } from "@/components/layout/SidebarVisibilityContext";
import { ThemeWrapper } from "@/components/theme/ThemeWrapper";
import { LanguageProvider } from "@/components/i18n/LanguageContext";
import { cookies } from "next/headers";
import { type ReactNode } from "react";
import type { ThemeMode } from "@/components/theme/utils/types/types";
import { cookiesThemeKey } from "@/utils/constants/constants";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import ThemeRegistry from "@/components/theme/ThemeRegistry";
import type { NavUser } from "@/components/navigation/AppNavigation";
import { auth0 } from "@/lib/auth0";
import { safeHttpUrl } from "@/utils/helpers/safeHttpUrl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gradfolio",
  description: "Generated by NPUA students",
};

/**
 * The signed-in user for the navigation, or null for a visitor. Display only:
 * which pages need a login is decided in proxy.ts, which fails closed. If the
 * session cannot be read here, the menu shows the signed-out state.
 */
async function navUser(): Promise<NavUser | null> {
  try {
    const session = await auth0.getSession();
    if (!session) return null;
    const { name, email, picture } = session.user;
    return {
      name: typeof name === "string" && name ? name : typeof email === "string" ? email : "",
      picture: typeof picture === "string" ? safeHttpUrl(picture) : undefined,
    };
  } catch (error) {
    console.error("layout: session unreadable", {
      error: error instanceof Error ? error.name : typeof error,
    });
    return null;
  }
}

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: Readonly<RootLayoutProps>) {
  const cookieStore = await cookies();

  const initialMode = cookieStore.get(cookiesThemeKey)?.value as ThemeMode | undefined;
  const user = await navUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ padding: 0, margin: 0 }}
      >
        <ThemeRegistry>
          <ThemeWrapper initialMode={initialMode}>
            <LanguageProvider>
              <SidebarVisibilityProvider>
                <SideBarWrapper user={user}>{children}</SideBarWrapper>
              </SidebarVisibilityProvider>
            </LanguageProvider>
          </ThemeWrapper>
        </ThemeRegistry>

        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
