import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SideBarWrapper } from "@/components/sidebar/SideBarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by NPUA students",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ padding: 0, margin: 0 }}
      >
        <SideBarWrapper>{children}</SideBarWrapper>
      </body>
    </html>
  );
}
